# Generated by Django 5.0.6 on 2024-05-27 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("points", models.IntegerField(default=0)),
                ("qr_code", models.ImageField(blank=True, upload_to="qr_codes/")),
            ],
        ),
    ]
